--Question 1
SELECT * FROM OFFICES;

--Question 2
SELECT EMPLOYEENUMBER FROM EMPLOYEES WHERE OFFICECODE = 1;

--Question 3
SELECT CUSTOMERNUMBER, CUSTOMERNAME, CONTACTFIRSTNAME, CONTACTLASTNAME, PHONE 
FROM CUSTOMERS
WHERE CITY = 'Paris';

--Question 4
SELECT CUSTOMERNUMBER, CUSTOMERNAME, CONTACTLASTNAME || ' ' || CONTACTFIRSTNAME AS CONTACTFULLNAME, PHONE 
FROM CUSTOMERS
WHERE COUNTRY = 'Canada';

--Question 5 <--- NOT SURE
SELECT CUSTOMERNUMBER FROM PAYMENTS
WHERE AMOUNT > 0;

--QUESTION 6
SELECT CUSTOMERNUMBER, CHECKNUMBER, AMOUNT
FROM PAYMENTS
WHERE AMOUNT > 65000 OR AMOUNT < 30000;

--QUESTION 7
SELECT * FROM ORDERS
WHERE STATUS = 'Cancelled';

--Question 8
SELECT PRODUCTCODE, PRODUCTNAME, BUYPRICE, MSRP, 
MSRP - BUYPRICE AS MARKUP, 
ROUND((100 * (MSRP - BUYPRICE)) / BUYPRICE, 1) AS PERCMARKUP
FROM PRODUCTS;

--Question 9 <--- NOT SURE
SELECT * FROM PRODUCTS
WHERE PRODUCTNAME LIKE '%co%';

--Question 10
SELECT * FROM CUSTOMERS
WHERE (CONTACTFIRSTNAME LIKE 'S%' OR CONTACTFIRSTNAME LIKE 's%') AND CONTACTFIRSTNAME LIKE '%e%' OR CONTACTFIRSTNAME LIKE '%E%';

--Question 11
INSERT INTO EMPLOYEES (EMPLOYEENUMBER, LASTNAME, FIRSTNAME, EXTENSION, EMAIL, JOBTITLE, OFFICECODE, REPORTSTO)
VALUES (13, 'Huggins', 'Matthew', 'x13', 'mhuggins2@myseneca.ca', 'Cashier', 4, 1088);

--Question 12
SELECT * FROM EMPLOYEES
WHERE EMPLOYEENUMBER = 13;

--Question 13
UPDATE EMPLOYEES
SET JOBTITLE = 'Head Cashier'
WHERE EMPLOYEENUMBER = 13;

--Question 14
INSERT INTO EMPLOYEES (EMPLOYEENUMBER, LASTNAME, FIRSTNAME, EXTENSION, EMAIL, JOBTITLE, OFFICECODE, REPORTSTO)
VALUES (14, 'Smith', 'John', 'x4333', 'jsmith3@myseneca.ca', 'Cashier', 4, 13);

--Question 15
DELETE FROM EMPLOYEES
WHERE EMPLOYEENUMBER = 13;
--The reason the delete command did not work is because Employee #14 is a child of Employee #13 meaning it is dependant on #13 so it can't be deleted.

--Question 16
DELETE FROM EMPLOYEES
WHERE EMPLOYEENUMBER = 14;

--Question 17 <--- NOT SURE
INSERT INTO EMPLOYEES (EMPLOYEENUMBER, LASTNAME, FIRSTNAME, EXTENSION, EMAIL, JOBTITLE, OFFICECODE, REPORTSTO)
SELECT 13, 'Huggins', 'Matthew', 'x13', 'mhuggins2@myseneca.ca', 'Cashier', 4, 1088 FROM DUAL
UNION ALL
SELECT 14, 'Smith', 'John', 'x4333', 'jsmith3@myseneca.ca', 'Cashier', 4, 1088 FROM DUAL;


--Question 18

DELETE FROM EMPLOYEES
WHERE EMPLOYEENUMBER = 13 OR EMPLOYEENUMBER = 14;


